# Generated by Django 5.0.2 on 2024-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0002_admin_plan_datatable_report_subscription_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
