# Generated by Django 5.0.2 on 2024-02-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0006_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataTableStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('notstarted', 'notstarted'), ('incompleted', 'Incompleted'), ('completed', 'Completed')], default='active', max_length=20)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_database.datatable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_database.customuser')),
            ],
            options={
                'unique_together': {('user', 'data_table')},
            },
        ),
    ]
