# Generated by Django 4.2.5 on 2024-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0008_faq_datatable_full_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='puzzle_no',
            field=models.CharField(max_length=100),
        ),
    ]
