# Generated by Django 4.2.5 on 2024-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0010_rename_report_logreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='benefits',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
