# Generated by Django 4.2.5 on 2024-03-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0012_remove_userdatatablestatus_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatable',
            old_name='puzzle_no',
            new_name='puzzle_id',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='task_no',
            new_name='task_id',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='full_id',
        ),
    ]
