# Generated by Django 5.0.3 on 2024-03-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0013_rename_puzzle_no_datatable_puzzle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatatablestatus',
            name='puzzle_locked',
            field=models.BooleanField(default=False),
        ),
    ]
