# Generated by Django 5.0.3 on 2024-03-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0014_userdatatablestatus_puzzle_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='puzzle_interview_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatable',
            name='puzzle_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='puzzle_video',
            field=models.FileField(upload_to='puzzle_videos/'),
        ),
    ]
