# Generated by Django 5.0.3 on 2024-03-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0015_datatable_puzzle_interview_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='puzzle_video',
            field=models.FileField(upload_to='puzzle_frontend/src/videos'),
        ),
    ]
