# Generated by Django 5.0.3 on 2024-03-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0016_alter_datatable_puzzle_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='PlanTable',
        ),
    ]
