# Generated by Django 5.0.3 on 2024-03-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0017_rename_plan_plantable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sub_amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='sub_plan_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='puzzle_database.plantable'),
            preserve_default=False,
        ),
    ]
