# Generated by Django 5.0.3 on 2024-04-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0019_remove_logreport_puzzle_no_remove_logreport_task_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_twostep_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='puzzle_frontend/src/profile_image'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='puzzle_code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatatablestatus',
            name='puzzle_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdatatablestatus',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatatablestatus',
            name='puzzle_status',
            field=models.CharField(choices=[('notstarted', 'notstarted'), ('incompleted', 'incompleted'), ('completed', 'completed')], default='notstarted', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdatatablestatus',
            name='task_status',
            field=models.CharField(choices=[('notstarted', 'notstarted'), ('incompleted', 'incompleted'), ('completed', 'completed')], default='notstarted', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdatatablestatus',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_in_puzzle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_in_task',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_database.plantable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_database.customuser')),
            ],
        ),
    ]
