# Generated by Django 5.0.3 on 2024-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_database', '0020_customuser_college_name_customuser_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='correct_answer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datatable',
            name='options',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
